#!/bin/zsh

# https://github.com/goreliu/zshguide/blob/master/03_Zsh-%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97%EF%BC%88%E7%AC%AC%E4%B8%89%E7%AF%87-%E5%AD%97%E7%AC%A6%E4%B8%B2%E5%A4%84%E7%90%86%E4%B9%8B%E8%BD%AC%E4%B9%89%E5%AD%97%E7%AC%A6%E5%92%8C%E6%A0%BC%E5%BC%8F%E5%8C%96%E8%BE%93%E5%87%BA%EF%BC%89.md#输出带颜色和特殊样式的字符串

print -nP '%F{black}[black 0] '
print -nP '%F{red}[red 1] '
print -nP '%F{green}[green 2] '
print -nP '%F{yellow}[yellow 3] '
print -nP '%F{blue}[blue 4] '
print -nP '%F{magenta}[magenta 5] '
print -nP '%F{cyan}[cyan 6] '
print -nP '%F{white}[white 7] '

print -P '%f%k%b%s'

print -nP '%S%F{black}[black 0]%s '
print -nP '%S%F{red}[red 1]%s '
print -nP '%S%F{green}[green 2]%s '
print -nP '%S%F{yellow}[yellow 3]%s '
print -nP '%S%F{blue}[blue 4]%s '
print -nP '%S%F{magenta}[magenta 5]%s '
print -nP '%S%F{cyan}[cyan 6]%s '
print -nP '%S%F{white}[white 7]%s '

print -P '%f%k%b%s\n'

print -nP '%K{black}         %k '
print -nP '%K{red}       %k '
print -nP '%K{green}         %k '
print -nP '%K{yellow}          %k '
print -nP '%K{blue}        %k '
print -nP '%K{magenta}           %k '
print -nP '%K{cyan}        %k '
print -nP '%K{white}         %k '

print -P '%f%k%b%s\n'

print -nP '%B%F{black}[black 0] '
print -nP '%B%F{red}[red 1] '
print -nP '%B%F{green}[green 2] '
print -nP '%B%F{yellow}[yellow 3] '
print -nP '%B%F{blue}[blue 4] '
print -nP '%B%F{magenta}[magenta 5] '
print -nP '%B%F{cyan}[cyan 6] '
print -nP '%B%F{white}[white 7] '

print -P '%f%k%b%s'

print -nP '%S%B%F{black}[black 0]%s '
print -nP '%S%B%F{red}[red 1]%s '
print -nP '%S%B%F{green}[green 2]%s '
print -nP '%S%B%F{yellow}[yellow 3]%s '
print -nP '%S%B%F{blue}[blue 4]%s '
print -nP '%S%B%F{magenta}[magenta 5]%s '
print -nP '%S%B%F{cyan}[cyan 6]%s '
print -nP '%S%B%F{white}[white 7]%s '

print -P '%f%k%b%s'
