#!/bin/bash

cd /home/goreliu/site
make start
./apps/aria2c/start

sleep 10

sudo ip route add 192.168.1.0/24 dev eth0 src 192.168.1.6 table 100
sudo ip route add default via 192.168.1.1 dev eth0 table 100
sudo ip rule add from 192.168.1.6 lookup 100

sudo ip route add 192.168.1.0/24 dev wlan0 src 192.168.1.7 table 200
sudo ip route add default via 192.168.1.1 dev wlan0 table 200
sudo ip rule add from 192.168.1.7 lookup 200

#sudo ip route add 192.168.1.0/24 dev wlan1 src 192.168.1.8 table 300
#sudo ip route add default via 192.168.1.8 dev wlan1 table 300
#sudo ip rule add from 192.168.1.8 lookup 300
