#!/bin/zsh

if (( $# == 0 )) {
    echo "$(<~/.cache/.cg)"
    return
}

cg_file=(${(f)"$(< ~/.cache/.cg)"})

if (( $1 > $#cg_file - 2 )) {
    echo "$(<~/.cache/.cg)"
} else {
    cd $cg_file[1]

    filename=$cg_file[$(( $1 + 2 ))]
    line=${filename#*:}
    line=$line[15,-1]
    line=${line%%\[m*}
    line=$line[1,-2]

    if [[ $line == <-> ]] {
        filename=${filename#*\[K}
        filename=${filename%%\[m*}
        filename=$filename[1,-2]
    } else {
        filename=${filename#*Binary file }
        filename=${filename% match*}
        line=0
    }

    echo $cg_file[1]/$filename[3,-1]

    vim +${line} ${filename}
}
